steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/my-app-repo-europe/my-app:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/my-app-repo-europe/my-app:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'flask-app'
  - '--image'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/my-app-repo-europe/my-app:latest'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/my-app-repo-europe/my-app:latest'
